- name: create new user
  tags: always
  ansible.builtin.user:
    name: yosh
    groups: root

- name: add sudoers file for david
  tags: always
  ansible.builtin.copy:
    src: sudoer_david
    dest: /etc/sudoers.d/david
    owner: root
    group: root
    mode: 0440

- name: add ssh key for david
  tags: always
  ansible.builtin.authorized_key:
    user: david
    key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGMjQBgwLrfIb5rOesYFMhwQDuUSh3BSqx1q40waIcY6 david@ubuntu-ws"
